#!/bin/bash

# Define colors for output
brd='\033[1;31m'            # bold + red
bgr='\033[1;32m'            # bold + green
rst='\033[0m'               # reset

# Welcome message
printf ">>>${bgr}afterparty-sign${rst}<<<\n"
printf "Copyright (C) 2015 Jan Grosser (email@jan-grosser.de)\n"
printf "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\n"
printf "This is free software: you are free to change and redistribute it.\n"
printf "There is NO WARRANTY, to the extent permitted by law.\n"

# Print help if any argument is present
if [ $# -gt 0 ]
then
    printf "\nUsage:\n"
    printf " $0 --help # Print help message\n"
    printf " echo \"12345678 87654321\" | $0\n"
    printf " cat keyfile.txt | $0\n\n"
    exit 0
fi

# Read configuration files
configs="/etc/afterparty.conf ${HOME}/.afterparty.conf"
for conf in ${configs}
do
    if [ -r "${conf}" ]
    then
        source ${conf}
    fi
done

# Convert key id to upper-case
mykeyid=${mykeyid^^}

# Test if GnuPG executable exist
if [ ! -f "${gpgbin}" -a ! -x "${gpgbin}" ]
then
    printf "\nERROR: Cannot find GnuPG executable.\n\n"
    exit 1
fi

# Test if key ID of variable ${mykeyid} is contained in the secret keyring
test_mykeyid=$( ${gpgbin} -K | grep ${mykeyid} | wc -l )
if [ ${test_mykeyid} -ne 1 ]
then
    printf "\nERROR: Key ${mykeyid} not contained in secret keyring.\n\n"
    exit 1
fi

# Determine the user language. If german, then user input for "yes" is key "j",
# otherwise key "y"
ans_yes="y"
if [[ ${LANG} == de_DE* ]]; then
    ans_yes="j"
fi

# Read list of keys from STDIN
input=$(</dev/stdin)

# Replace all existing delimiters "," by " "
input=${input//,/ }

# Loop over the keys, or at least what we assume to be keys ;)
for key in ${input}
do
    # Convert key to upper-case
    key=${key^^}

    # Fetch/update key from keyserver
    printf "\n>>> Fetch key ${bgr}${key}${rst} from keyserver . . .\n"
    $gpgbin --keyserver ${keysrv} --recv-keys ${key} > /dev/null 2>&1
    
    # Go ahead only if key was found on the keyserver. Otherwise print warning
    # message and proceed with following key
    if [ $? -eq 0 ]; then
        # Signing key. Use the user dialog provided by GnuPG.
        ${gpgbin} -u ${mykeyid} --sign-key ${key}
        
        # Ask user if key shall be uploaded to keyserver
        printf "\n\nUpload signed key ${key} to keyserver (${ans_yes}/N)? "
            read answer </dev/tty
        if [ "${answer^^}" == "Y" ]; then
            printf "Upload to keyserver . . .\n"
            # ${gpgbin} --keyserver ${keysrv} --send-key ${key}
        fi

        # Ask user if key shall be mailed to key owner
        # Has to be written

    else
        printf "\nKey ${key} was not found on keyserver ${keysrv}.\n"
    fi
done

